package com.model;

/**
 * TGoods generated by MyEclipse Persistence Tools
 */

public class TGoods implements java.io.Serializable
{

	private Integer goodsId;
	private Integer catelogId;
	private String goodsName;

	private String goodsJieshao;
	private String goodsPic;
	private Integer goodsShichangjia;
	private Integer goodsTejia;
	private Integer kucun;

	private String fabushi;
	private String goodsDel;
	
	
	public String getFabushi()
	{
		return fabushi;
	}
	public void setFabushi(String fabushi)
	{
		this.fabushi = fabushi;
	}
	public String getGoodsDel()
	{
		return goodsDel;
	}
	public void setGoodsDel(String goodsDel)
	{
		this.goodsDel = goodsDel;
	}
	public Integer getGoodsId()
	{
		return goodsId;
	}
	public void setGoodsId(Integer goodsId)
	{
		this.goodsId = goodsId;
	}
	public String getGoodsName()
	{
		return goodsName;
	}
	public void setGoodsName(String goodsName)
	{
		this.goodsName = goodsName;
	}
	
	public Integer getKucun()
	{
		return kucun;
	}
	public void setKucun(Integer kucun)
	{
		this.kucun = kucun;
	}
	public String getGoodsPic()
	{
		return goodsPic;
	}
	public void setGoodsPic(String goodsPic)
	{
		this.goodsPic = goodsPic;
	}
	public Integer getGoodsShichangjia()
	{
		return goodsShichangjia;
	}
	public void setGoodsShichangjia(Integer goodsShichangjia)
	{
		this.goodsShichangjia = goodsShichangjia;
	}
	public Integer getGoodsTejia()
	{
		return goodsTejia;
	}
	public void setGoodsTejia(Integer goodsTejia)
	{
		this.goodsTejia = goodsTejia;
	}
	public Integer getCatelogId()
	{
		return catelogId;
	}
	public void setCatelogId(Integer catelogId)
	{
		this.catelogId = catelogId;
	}
	public String getGoodsJieshao()
	{
		return goodsJieshao;
	}
	public void setGoodsJieshao(String goodsJieshao)
	{
		this.goodsJieshao = goodsJieshao;
	}

}